### ISSUE TITLE
Suggestions on website UX

### ISSUE THREAD

**Issue by reasonablecode** [TheProfesseer/TheProfesseer.github.io#1]
1. Screenshots of Dashboard - needs a placeholder
2. Add team - Ayush, Susan, Ajay, Atibhi. Everyone needs to send a short bio. 
3. Please pick colors. I like dark shades of blue <img width="674" alt="image" src="https://github.com/user-attachments/assets/6720623c-455f-4f23-ab40-e86e216d1417"> and maroon <img width="680" alt="image" src="https://github.com/user-attachments/assets/c934d371-3818-4843-a688-537b95383779"> over red. I like the gold.
4. Add a section on "Our Work / Our Research" - this should have all useful links from the legal systems, even if it's repeat from xkdr website. 
5. Minor, but please bottom align these <img width="836" alt="image" src="https://github.com/user-attachments/assets/c609be7a-84e2-428e-a101-800f0b6660b2">

**Comment by bhargavizaveri** [comment]
Did a quick review this morning:

1. The website is taking a bit long to load on the desktop and the phone. 

2. Some comments on the following section of the website:
 <img width="1168" alt="Screenshot 2024-12-06 at 10 46 06 AM" src="https://github.com/user-attachments/assets/d16ce313-d4e9-4853-807e-56478909cdbe">

- The way the nos. have been shown doesn't look nice. Even if a ticker is not possible for now, please put them horizontally in big font.
- Also, these nos. show coverage. Please delete the line "focusing on what matters most". If you want to retain it, please keep it above the "Know your Judge", "Know your costs", etc.

3. I am assuming the images will be re-organized and substituted with the screenshots, and color palette will be changed.
