### ISSUE TITLE
Prof Owl not visible on mobile

### ISSUE THREAD

**Issue by reasonablecode** [TheProfesseer/TheProfesseer.github.io#3]
<img width="528" alt="image" src="https://github.com/user-attachments/assets/638431d4-f61c-4869-b891-d9f9f5bf1109">

**Comment by ayushpatnaikgit** [comment]
Wasn't sure where to put it, so disabled on phone for now.

**Comment by reasonablecode** [comment]
Cool. Thought it was a bug. Closing this then.
