### ISSUE TITLE
Screenshots for website

### ISSUE THREAD

**Issue by pavithra-manivannan** [TheProfesseer/TheProfesseer.github.io#5]
BZ and I worked on the content for the screenshots (attached). 
Once Ayush finalises the color palette, Atibhi or I will generate the final screenshots. 
![2](https://github.com/user-attachments/assets/3da5b7f4-b136-4552-8b8d-b6a389d176c4)
![1](https://github.com/user-attachments/assets/c4e713fd-0bd0-4117-b9c1-c70e83a62501)

**Comment by ayushpatnaikgit** [comment]
Can you add in the `images` directory? Create another folder called screenshots.

**Comment by ayushpatnaikgit** [comment]
Ideally want 6 of them.

**Comment by pavithra-manivannan** [comment]
Ya. These are not final. Will update the images folder once we get the final ones.

**Comment by ayushpatnaikgit** [comment]
Added. If you want to change, just update images/screenshots.
